### PR TITLE
Fix: user defined path to font was ignored in `add_font` when `uni=True

### PR DESCRIPTION
**Pull request by Lucas-C**
Copied from https://github.com/reingart/pyfpdf/pull/167

Thanks @xitrushiy!

### CODE REVIEW

**Comment by alexanderankin** [comment]
looks like it was fixed in https://github.com/alexanderankin/pyfpdf/commit/2f55ab2696c0d9220647fd50a0241dcbf2fa5558

**Comment by Lucas-C** [comment]
Indeed! Sorry, I thought there were 2 distinct dicts :)
Closing this as it is already fixed!

**Comment by alexanderankin** [comment]
looks like it got overwritten or i never merged it right in the first place???

**Comment by Lucas-C** [comment]
No you did! :)
You fixed the `font_dict` dictionnary directly, a few lines above.
So this is not an issue anymore, and this PR brings nothing new, that's why I closed it.

**Comment by alexanderankin** [comment]
its not actually showing the dict access anywhere in the search history:

```
$ git checkout 98ea55c5
HEAD is now at 98ea55c Auto-format code with black
$ git blame fpdf/fpdf.py -L 645,655
4dbbe52d fpdf.py      (Mariano Reingart 2012-06-16 22:26:22 -0300 645)                 font_dict = {
98ea55c5 fpdf/fpdf.py (Lucas Cimon      2021-01-03 11:48:53 +0100 646)                     "name": re.sub("[ ()]", "", ttf.fullName),
98ea55c5 fpdf/fpdf.py (Lucas Cimon      2021-01-03 11:48:53 +0100 647)                     "type": "TTF",
98ea55c5 fpdf/fpdf.py (Lucas Cimon      2021-01-03 11:48:53 +0100 648)                     "desc": desc,
98ea55c5 fpdf/fpdf.py (Lucas Cimon      2021-01-03 11:48:53 +0100 649)                     "up": round(ttf.underlinePosition),
98ea55c5 fpdf/fpdf.py (Lucas Cimon      2021-01-03 11:48:53 +0100 650)                     "ut": round(ttf.underlineThickness),
98ea55c5 fpdf/fpdf.py (Lucas Cimon      2021-01-03 11:48:53 +0100 651)                     "ttffile": ttffilename,
98ea55c5 fpdf/fpdf.py (Lucas Cimon      2021-01-03 11:48:53 +0100 652)                     "fontkey": fontkey,
98ea55c5 fpdf/fpdf.py (Lucas Cimon      2021-01-03 11:48:53 +0100 653)                     "originalsize": os.stat(ttffilename).st_size,
98ea55c5 fpdf/fpdf.py (Lucas Cimon      2021-01-03 11:48:53 +0100 654)                     "cw": ttf.charWidths,
bd608e48 fpdf/fpdf.py (Dave Ankin       2017-03-16 09:26:17 -0400 655)                 }
$ git checkout HEAD^
Previous HEAD position was 98ea55c Auto-format code with black
HEAD is now at 196bbc7 Getting rid of six & py3k module now that we only support Python 3
$ git blame fpdf/fpdf.py -L 625,635
bd608e48 fpdf/fpdf.py (Dave Ankin       2017-03-16 09:26:17 -0400 625)                 'up'          : font_dict['up'],
bd608e48 fpdf/fpdf.py (Dave Ankin       2017-03-16 09:26:17 -0400 626)                 'ut'          : font_dict['ut'],
bd608e48 fpdf/fpdf.py (Dave Ankin       2017-03-16 09:26:17 -0400 627)                 'cw'          : font_dict['cw'],
bd608e48 fpdf/fpdf.py (Dave Ankin       2017-03-16 09:26:17 -0400 628)                 'ttffile'     : font_dict['ttffile'],

**Pull request closed without merging**
