### PR TITLE
Fixing .ttf font loading & rendering - close #20

### LINKED ISSUE #20: Adding font leads to UnpicklingError
I tried to use the Computer Modern (CM) fonts (https://ctan.org/pkg/bakoma-fonts) with pyfpdf but failed.
Also tried to add the font via the `.ttf` file but I get a `UnpicklingError: invalid load key, '\x00'` exception.

```
pdf.add_font('cmss12', fname='cmss12.ttf')
pdf.set_font('cmss12', '', 16)
```

### PR DESCRIPTION
**Pull request by Lucas-C**

### CODE REVIEW

**Comment by alexanderankin** [comment]
huh... that was quick! what does the test coverage look like after this? higher?

**Comment by Lucas-C** [comment]
I didn't look at it :)

**Comment by alexanderankin** [comment]
so fonts just needed some `.decode`'s and the one is 'cid' out of range check?

**Comment by alexanderankin** [comment]
also @Lucas-C in the future, can you make sure to "Squash and Merge" and not just merge? thanks. that way changes are atomic.

**Pull request merged**
