### PR TITLE
Improved font handling

### PR DESCRIPTION
**Pull request by cgfrost**
This commit improves the handling of fonts by the HTML mixin. There are
still improvements to be made but the behaviour is now much more
consistent. Also removed a pointless sample test and adding ignore files
for devs using IntelliJ.

The behaviour of FONT, PRE, P, BR and HR now more closely follows that
defined in w3c tag reference (https://www.w3schools.com/tags/default.asp).

Line height issues have been mostly fixed by correctly using the self.h
value when writing text out to the pdf. This was mostly an issue with links.

These improvements have been achieved by making more use of the font
stack to push and pop changes as tags are opened and closed. I don't
have time today to apply similar improvements to the style and heading
tags and tables but I will do so in the future.

### CODE REVIEW

**Comment by cgfrost** [comment]
It would be great to get a new release if this all looks OK to you.

**Comment by cgfrost** [comment]
Just noticed my IDE went and changed the formatting a little, added in some spaces. Hope that's ok.

**Comment by mkedavid** [comment]
ill check it out either today or tomorrow and maybe make some changes then release.

**Comment by alexanderankin** [comment]
ill check it out either today or tomorrow and maybe make some changes then
release.

one thing right away is the unescape is imported from py3k because the
library supports Python2 and 3 and according to semantic versioning id have
to increase the version number up to 3 to not break programs.

**Comment by cgfrost** [comment]
Hi. Thank you.

I moved back to the previous unescape, I hope that's the only Python 3 I introduced.

I also added a fixed bug where an image could be printed off the end of the page. If that would happen a new page is added to the pdf before drawing the image. I've also changed the behaviour of the HR tag, I think it's now more in line with the meaning of the tag and probably more useful to end users.

**Comment by cgfrost** [comment]
Thank you.

**Pull request merged**
