### PR TITLE
Getting rid of six & py3k module now that we only support Python 3

### PR DESCRIPTION
**Pull request by Lucas-C**
Code clean-up : getting rid of `furure` & `six` dependencies,
and the internal `py3k` module now that we only support Python 3.

### CODE REVIEW

**Comment by Lucas-C** [comment]
The tests are ✔️ for this PR: https://github.com/Lucas-C/pyfpdf/actions/runs/459006978

**Comment by alexanderankin** [comment]
the docs folder is the github dot io site which has several versions of the docs on it, like epydocs et al

**Comment by Lucas-C** [comment]
@alexanderankin : I'm not sure to understand your comment, sorry :(
Is it a question or suggestion ?

I got rid of `epydoc` in this PR as it is not compatible with Python 3.

This PR also adds [black](https://github.com/psf/black) as a mandatory code formatter: strict code formatting is checked by the GitHub Actions pipeline.

**Comment by alexanderankin** [comment]
yeah sorry im sure you were aware, i was just surprised to see a lot of red in the docs about a pr which is billed as pertaining to py3k but i didnt realize epydocs is out. alrighty then.

**Review by alexanderankin — APPROVED** [review]

**Comment by alexanderankin** [comment]
every time i think about some major changes like this it makes me kick myself even more for not having made font tests but thats still a total mystery and ive tried several times and failed now, so if the already working tests work thats probably as good as it gets for now.

**Comment by alexanderankin** [comment]
yes thats the link i had in mind

**Pull request merged**
